.TH "C:/QTT/Prufer Directory Reference" 3 "Mon Oct 31 2022" "Version 1.6" "Prufer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Prufer Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBform\&.cpp\fP"
.br
.ti -1c
.RI "file \fBform\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBnode\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnode\&.h\fP"
.br
.ti -1c
.RI "file \fBtree\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtree\&.h\fP"
.br
.in -1c
