.TH "C:/QTT/Prufer/form.h" 3 "Mon Oct 31 2022" "Version 1.6" "Prufer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Prufer/form.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include 'tree\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForm\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Prufer from the source code\&.
