.TH "Form" 3 "Mon Oct 31 2022" "Version 1.6" "Prufer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Form
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <form\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~Form\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Form::Form (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "Form::~Form ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prufer from the source code\&.
