.TH "C:/QTT/Prufer/main.cpp" 3 "Mon Oct 31 2022" "Version 1.6" "Prufer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Prufer/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QApplication>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prufer from the source code\&.
