.TH "C:/QTT/Prufer/node.h" 3 "Mon Oct 31 2022" "Version 1.6" "Prufer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Prufer/node.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Prufer from the source code\&.
