.TH "Node" 3 "Mon Oct 31 2022" "Version 1.6" "Prufer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <node\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (int \fBinfo\fP)"
.br
.ti -1c
.RI "\fBNode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBinfo\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBparent\fP"
.br
.ti -1c
.RI "vector< \fBNode\fP * > \fBchilds\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Node::Node (int info)"

.SS "Node::Node ()"

.SH "Member Data Documentation"
.PP 
.SS "vector<\fBNode\fP*> Node::childs"

.SS "int Node::info"

.SS "\fBNode\fP* Node::parent"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prufer from the source code\&.
