.TH "md__c_1__q_t_t__sborka_client-singleton__r_e_a_d_m_e" 3 "Sat Oct 29 2022" "Version 1.6" "Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__q_t_t__sborka_client-singleton__r_e_a_d_m_e \- PTechnologies 
Задачей нашего проекта является тестирование пользователей в области дискретной математики\&. Пользователи смогут проработать такие задачи как:
.PP
.IP "1." 4
Нахождение совершенного паросочетания в двудольном графе;
.IP "2." 4
Нахождение систем для различных представителей для множеств;
.IP "3." 4
Построение наибольшего по весу совершенного паросочетания в полном двудольном графе;
.IP "4." 4
Нахождение максимального потока и минимального разреза между вершинами в транспортной сети с ориентированным графом\&.
.PP
.PP
Также для контроля знаний пользователи смогут просматривать свою статистику\&. 
