.TH "C:/QTT/Sborka/client-singleton/singletonclient.cpp" 3 "Sat Oct 29 2022" "Version 1.6" "Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/client-singleton/singletonclient.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'singletonclient\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Client from the source code\&.
