.TH "SingletonDestroyer" 3 "Sat Oct 29 2022" "Version 1.6" "Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingletonDestroyer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <singletonclient\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~SingletonDestroyer\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (\fBsingletonclient\fP *p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SingletonDestroyer::~SingletonDestroyer ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void SingletonDestroyer::initialize (\fBsingletonclient\fP * p)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Client from the source code\&.
