.TH "C:/QTT/Sborka/client-singleton/singletonclient.h" 3 "Sat Oct 29 2022" "Version 1.6" "Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/client-singleton/singletonclient.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QTcpSocket>\fP
.br
\fC#include <QtNetwork>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSingletonDestroyer\fP"
.br
.ti -1c
.RI "class \fBsingletonclient\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Client from the source code\&.
