.TH "C:/QTT/Sborka/server Directory Reference" 3 "Sat Oct 29 2022" "Version 1.6" "Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/server Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatabase\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdatabase\&.h\fP"
.br
.ti -1c
.RI "file \fBfunctionsforserver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfunctionsforserver\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmytcpserver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmytcpserver\&.h\fP"
.br
.in -1c
