.TH "C:/QTT/Sborka/server/database.h" 3 "Sat Oct 29 2022" "Version 1.6" "Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/server/database.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDebug>\fP
.br
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QSqlError>\fP
.br
\fC#include <QSqlRecord>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataBaseDestroyer\fP"
.br
.ti -1c
.RI "class \fBDataBase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Server from the source code\&.
