.TH "DataBaseDestroyer" 3 "Sat Oct 29 2022" "Version 1.6" "Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataBaseDestroyer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <database\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~DataBaseDestroyer\fP ()"
.br
.ti -1c
.RI "void \fBinitialize\fP (\fBDataBase\fP *p)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataBaseDestroyer::~DataBaseDestroyer ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void DataBaseDestroyer::initialize (\fBDataBase\fP * p)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Server from the source code\&.
