.TH "C:/QTT/Sborka/server/functionsforserver.h" 3 "Sat Oct 29 2022" "Version 1.6" "Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/server/functionsforserver.h
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QByteArray \fBparsing\fP (QString data_from_client)"
.br
.ti -1c
.RI "QByteArray \fBauth\fP (QString log)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QByteArray auth (QString log)"

.SS "QByteArray parsing (QString data_from_client)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Server from the source code\&.
