.TH "C:/QTT/Sborka/server/main.cpp" 3 "Sat Oct 29 2022" "Version 1.6" "Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/server/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QCoreApplication>\fP
.br
\fC#include 'mytcpserver\&.h'\fP
.br
\fC#include 'database\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Server from the source code\&.
