.TH "C:/QTT/Sborka/inter/authorize.h" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/inter/authorize.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include 'functionsforclient\&.h'\fP
.br
\fC#include 'registration\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthorize\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GUI from the source code\&.
