.TH "Authorize" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Authorize
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <authorize\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBauthCorrect\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthorize\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~Authorize\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Authorize::Authorize (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "Authorize::~Authorize ()"

.SH "Member Function Documentation"
.PP 
.SS "void Authorize::authCorrect ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GUI from the source code\&.
