.TH "C:/QTT/Sborka/inter Directory Reference" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/inter Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauthorize\&.cpp\fP"
.br
.ti -1c
.RI "file \fBauthorize\&.h\fP"
.br
.ti -1c
.RI "file \fBfunctionsforclient\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfunctionsforclient\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBregistration\&.cpp\fP"
.br
.ti -1c
.RI "file \fBregistration\&.h\fP"
.br
.ti -1c
.RI "file \fBtask1\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtask1\&.h\fP"
.br
.ti -1c
.RI "file \fBtask2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtask2\&.h\fP"
.br
.ti -1c
.RI "file \fBtask3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtask3\&.h\fP"
.br
.ti -1c
.RI "file \fBtask4\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtask4\&.h\fP"
.br
.in -1c
