.TH "Registration" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Registration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <registration\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBauthCorrect\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegistration\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~Registration\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Registration::Registration (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "Registration::~Registration ()"

.SH "Member Function Documentation"
.PP 
.SS "void Registration::authCorrect ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GUI from the source code\&.
