.TH "C:/QTT/Sborka/inter/registration.cpp" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/QTT/Sborka/inter/registration.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'registration\&.h'\fP
.br
\fC#include 'ui_registration\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for GUI from the source code\&.
