.TH "task1" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task1
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task1\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBauthCorrect\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtask1\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~task1\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "task1::task1 (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "task1::~task1 ()"

.SH "Member Function Documentation"
.PP 
.SS "void task1::authCorrect ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GUI from the source code\&.
