.TH "task3" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task3\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBauthCorrect\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtask3\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~task3\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "task3::task3 (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "task3::~task3 ()"

.SH "Member Function Documentation"
.PP 
.SS "void task3::authCorrect ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GUI from the source code\&.
