.TH "task4" 3 "Sat Oct 29 2022" "Version 1.6" "GUI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task4
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task4\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBauthCorrect\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtask4\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~task4\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "task4::task4 (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "task4::~task4 ()"

.SH "Member Function Documentation"
.PP 
.SS "void task4::authCorrect ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GUI from the source code\&.
